# Generated by Django 5.0.14 on 2026-09-27 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgenteSecretConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_secret', models.CharField(default='gsconsole-gemini-secret', max_length=100, unique=True)),
                ('origem', models.CharField(default='Google Cloud Secret Manager / gsconsole', max_length=100)),
                ('ativo', models.BooleanField(default=True)),
                ('modelo_padrao', models.CharField(default='gemini-flash-latest', max_length=80)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConversaAgenteSessao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_id', models.IntegerField(default=42, unique=True)),
                ('cliente_nome', models.CharField(default='Cliente Itaú', max_length=150)),
                ('cliente_genero', models.CharField(default='F', max_length=1)),
                ('score_comportamental', models.IntegerField(default=750)),
                ('indice_corte', models.CharField(default='CTX-750-ALPHA', max_length=50)),
                ('data_corte_fixa', models.CharField(default='2025-12-22', max_length=20)),
                ('horario_casado', models.CharField(default='14:35:20', max_length=20)),
                ('iniciado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MensagemAgenteRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(max_length=20)),
                ('conteudo', models.TextField()),
                ('secret_utilizado', models.CharField(default='gsconsole:GEMINI_API_KEY', max_length=100)),
                ('horario_registro', models.CharField(default='14:35:20', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('sessao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='context_agent_datadriven.conversaagentesessao')),
            ],
        ),
    ]
