# Generated by Django 5.0.14 on 2026-09-27 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context_agent_datadriven', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessaoPerfilUsuario',
            fields=[
                ('sessao_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('usuario_json', models.TextField()),
                ('criada_em', models.FloatField(db_index=True)),
            ],
        ),
    ]
