# Generated by Django 5.0.14 on 2026-09-27 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmacaoPlano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dono', models.CharField(max_length=128)),
                ('pedido_id', models.CharField(max_length=80)),
                ('digest', models.CharField(max_length=64)),
                ('resposta_json', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PlanoAtivo',
            fields=[
                ('dono', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('ref', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='PlanoIAgora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dono', models.CharField(max_length=128)),
                ('ref', models.CharField(max_length=64)),
                ('estado_json', models.TextField()),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='confirmacaoplano',
            constraint=models.UniqueConstraint(fields=('dono', 'pedido_id'), name='confirmacao_plano_dono_pedido'),
        ),
        migrations.AddConstraint(
            model_name='planoiagora',
            constraint=models.UniqueConstraint(fields=('dono', 'ref'), name='plano_iagora_dono_ref'),
        ),
    ]
