# Generated by Django 5.0.14 on 2026-09-27 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaFluxoConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_fluxo', models.CharField(default='FLUXO_AUDITORIA_PADRAO', max_length=50, unique=True)),
                ('saudacao_template', models.CharField(default='Que bom ter você aqui,[VARIAVEL_NOME] !', max_length=255)),
                ('texto_1_neutro_p1', models.TextField(default='Hoje, seu dinheiro está concentrado no presente, deixando pouco espaço para imprevistos e planos futuros.')),
                ('texto_1_neutro_p2', models.TextField(default='Pequenas mudanças podem trazer mais equilíbrio. Você já sabe onde está, chegou a hora de decidir seu próximo passo.')),
                ('texto_2_masculino_p1', models.TextField(default='Hoje, seu dinheiro está concentrado no presente, deixando pouco espaço para imprevistos e planos futuros.')),
                ('texto_2_masculino_p2', models.TextField(default='Pequenas mudanças podem trazer mais equilíbrio. Você já sabe onde está, chegou a hora de decidir seu próximo passo.')),
                ('texto_3_feminino_p1', models.TextField(default='Hoje, seu dinheiro está concentrado no presente, deixando pouco espaço para imprevistos e planos futuros.')),
                ('texto_3_feminino_p2', models.TextField(default='Pequenas mudanças podem trazer mais equilíbrio. Você já sabe onde está, chegou a hora de decidir seu próximo passo.')),
                ('botao_proximo', models.CharField(default='E agora?', max_length=50)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClienteRegistro',
            fields=[
                ('cliente_id', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('primeiro_nome', models.CharField(max_length=80)),
                ('genero', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino')], max_length=1)),
                ('score_comportamental', models.IntegerField(default=500)),
                ('indice_corte', models.CharField(max_length=50)),
                ('segmento', models.CharField(default='Itaú Varejo', max_length=50)),
                ('saldo_estimado', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('limite_cartao', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('diretriz_comportamental', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'recomendacao_clienteregistro',
            },
        ),
        migrations.CreateModel(
            name='FeatureFlagInteracaoTelaIAI',
            fields=[
                ('codigo', models.CharField(default='CHAVE_INTEIRACAO_TELA_IAI', max_length=60, primary_key=True, serialize=False)),
                ('nome', models.CharField(default='Ponto de Inteiração Tela-IAI', max_length=120)),
                ('chave_ativa', models.BooleanField(default=True, help_text='Chave ON (True) / OFF (False). Quando ligada (ON), ativa o modo Neutro padrão.')),
                ('descricao', models.TextField(default='Controla se a tela de auditoria aplica o template Neutro universal ou mantém bifurcação estrita.')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlanilhaProdutoRegistro',
            fields=[
                ('codigo', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('produto', models.CharField(max_length=150)),
                ('categoria', models.CharField(max_length=100)),
                ('taxa_ou_retorno', models.CharField(max_length=100)),
                ('carencia_prazo', models.CharField(max_length=100)),
                ('score_minimo', models.IntegerField(default=0)),
                ('beneficio_chave', models.TextField()),
                ('afinidade_f', models.IntegerField(default=85)),
                ('afinidade_m', models.IntegerField(default=85)),
            ],
        ),
    ]
